#pragma once
#include "../api.h"
#include "../type.h"
  
typedef enum simplegl_status
{
    SIMPLEGL_STATUS_SUCCESS = 0,
    SIMPLEGL_STATUS_UNSUCCESSFUL, 
    SIMPLEGL_STATUS_STACK_OUT_OF_BOUNDS,
    SIMPLEGL_STATUS_PROGRAM_EXITED,
    SIMPLEGL_STATUS_PROGRAM_CRASHED,
    SIMPLEGL_STATUS_NOT_IMPLEMENTED,
    SIMPLEGL_STATUS_OBJECT_NAME_DOES_NOT_EXIST,
    SIMPLEGL_STATUS_ALLOCATION_ERROR,
    SIMPLEGL_STATUS_ENCODING_ERROR,
    SIMPLEGL_STATUS_INVALID_TOKEN,
    SIMPLEGL_STATUS_INVALID_OPCODE,
    SIMPLEGL_STATUS_INVALID_PARAMETER,
} simplegl_status_t;

#define SIMPLEGL_SUCCESS(status) ((status) == SIMPLEGL_STATUS_SUCCESS)
#define SIMPLEGL_REQUIRE_SUCCESS(var, label, status) SIMPLEGL_REQUIRE(SIMPLEGL_SUCCESS((status) = (var)), label)

const pchar SIMPLEGL_API simplegl_get_status_string(simplegl_status_t status);
